### ISSUE TITLE
Could this work with just the browser from p2p?

### ISSUE THREAD

**Issue by jimmywarting** [pion/offline-browser-communication#9]
I just discovered that there is a way to generate certificates that you can generate in the browser using [RTCPeerConnection.generateCertificate](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/generateCertificate)

it's also possible to store this cert in indexedDB. and construct a peer connection using `new RTCPeerConnection({certificates})` 

i have no understanding of why you would want to create your own certificates and store it in the indexedDB... haven't find any article/demo of someone who are using it of how and why you want to use own certificates
 
is it so you could create some kind of “reusable offer/answer”?

**Comment by Sean-Der** [comment]
Hey @jimmywarting, sorry for the delay.

Yes you can store them! This was cited as a use case in [webrtc-pc](https://www.w3.org/TR/webrtc/#dom-rtcconfiguration-certificates)

The last issue is that a RTCPeerConnection listens on a random port. A good solution to that could be [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem). I don't know how many attempts we get, but that could be a good first step.

Talking over GitHub issues is hard (since Pion has so many). If you want to chat I am available on [Slack](https://pion.ly/slack) and find this super interesting!

**Comment by guest271314** [comment]
Did you get this working?

**Comment by jimmywarting** [comment]
I never did anything with `RTCPeerConnection.generateCertificate`...
I would like to know how you could make use of it... 
eg if it's possible to establish a p2p connection without signaling (if it's at all possible - i don't know)

**Comment by guest271314** [comment]
My use case is communication between different parts of the same browser and same machine. One would think something could be hardcoded. During experiments I found `icecandidate` event does not fire when offline. The closest I got was using an extension `ServiceWorker` and offscreen document for signaling for the ability to stream data to arbitrarary tabs https://github.com/guest271314/offscreen-webrtc. Reading this https://stackoverflow.com/a/29418087 it appears a lot has to be in order. Then we have this repository...

**Comment by WofWca** [comment]
First of all, I believe this approach can only work on local networks (i.e. you can't connect machines over the Internet), because it relies on mDNS, which, AFAIK, doesn't work on the Internet.
Secondly, you probably can't connect two browsers on separate machines on a local network without hard-coding an IP address of at least one of them. This is because
  1. As @Sean-Der stated, [the WebRTC browser spec](https://w3c.github.io/webrtc-pc/) does not allow you to control the ports that the browser uses, unlike Pion:
  https://github.com/pion/offline-browser-communication/blob/3d2994ac1f93dbc54e4799e513e54d5c718e16a3/server.go#L37
  2. Browser WebRTC spec also doesn't allow you to control mDNS names that the browser uses, unlike Pion:
  https://github.com/pion/offline-browser-communication/blob/3d2994ac1f93dbc54e4799e513e54d5c718e16a3/server.go#L34

> My use case is communication between different parts of the same browser and same machine

For the case when the peers are on the same machine, the knowing the IP/mDNS is not a requirement, since each peer knows the the other peer has the same IP, but there is still the problem of ports.

To [communicate just between browser tabs](https://stackoverflow.com/questions/28230845/communication-between-tabs-or-windows), I'd also consider `localStorage`, cookies, `postMessage`, `BroadcastChannel`.

**Comment by guest271314** [comment]
I'm not trying to just communicate between tabs. I can do that here https://github.com/guest271314/offscreen-webrtc and here https://github.com/guest271314/sw-transfer-stream, and the approach descrined here https://github.com/guest271314/requestNativeScripts.

What I noticed when testing the former is that WebRTC does not work offline. 

My use case is using [libdatachannel](https://github.com/paullouisageneau/libdatachannel) offline on the same machine from browser to local application.
